home_page: Home.md # filepath under /source/
menu_page: Menu.md # filepath under /source/
author_img: # filepath of author image
favicon_url: favicon.jpg # filepath of favicon

zoom_image: true
codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  highlight_theme: normal

google_analytics: # UA-XXXXX-Y
