home_page: Home.md # filepath under /source/
menu_page: Menu.md # filepath under /source/
author_img: favicon.jpg
favicon_url: favicon.jpg # filepath of favicon

zoom_image: true

google_analytics: # UA-XXXXX-Y
